### ISSUE TITLE
Sending data slow

### ISSUE THREAD

**Issue by wim-vogt** [NordicSemiconductor/Android-nRF-Toolbox#10]
Hi,
Why android dfu send data much slower rate than ios，What I can do operations to accelerate the transmission speed?My device is the nexus 4, version 4.4.4

**Comment by philips77** [comment]
Hi, 
On Android the speed depends on the device, or rather the chip manufacturer. Nexus 4 and 7 are the slowest devices, actually. They have the same Bluetooth chip. They both may send just one packet each interval connection (or receive 3 notifications). In comparison, Nexus 5, 6, 9 or Samsungs may send and receive up to 4 packets. I also tested LG F60 which can send 6 packets.
As the interval connection depends on the firmware and is pretty constant, number of packets sent makes a significant difference. You may send either 1 or 4, or 6 packets (20 bytes each) each interval (for example each 7.5ms or 30ms.).

There is not much you can do to speed it up. If you are developing your proprietary protocol you may try to limit the data you send, but in case of DFU nothing can be done, as you have to send the whole firmware.
