### ISSUE TITLE
Cannot evaluate module dfu

### ISSUE THREAD

**Issue by jijunpeng** [NordicSemiconductor/Android-nRF-Toolbox#12]
The "build.gradle" file in module app has add module "dfu", but it cannot be compiled correctly.

**Comment by philips77** [comment]
Hi,

Version 1.16.0 requires the DFU Library project also cloned to the same root directory, and called **DFULibrary**, as described in README file. However, I've just pushed new version which is importing this lib from *jcenter* repository and this is no longer needed. The project should now copomile out of the box.

Best Regards,
Aleksander
