### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by chipwang** [NordicSemiconductor/Android-nRF-Toolbox#16]
Apple MacBookPro: Eclipse+SDK 4.4.2 compile error,help me!
Image link:  http://pan.baidu.com/s/1boGosKf

**Comment by mostafaberg** [comment]
Doesn't seem to be compilation issues, You're missing some resources, if you haven't manually moved things around, try to clear the caches and pull the repo in a new directory and that should sort it out, if not then check the contents of your Manifest file to see if the directories resolve to correct paths, if you've resolved the issue please remeber to close the issue

**Comment by philips77** [comment]
Hi, the link above does not work any more. I'm closing the issue. Reopen if if you still have any problems related to this.
