### ISSUE TITLE
.idea directory

### ISSUE THREAD

**Issue by SlawomirOnyszko** [NordicSemiconductor/Android-nRF-Toolbox#18]
.idea directory should be removed from remote repository.

**Comment by philips77** [comment]
You're right. I think also the *.iml files should be removed.

**Comment by SlawomirOnyszko** [comment]
You're right too. It could be done like this: `git rm -r --cached .idea` etc.

**Comment by philips77** [comment]
It has been now removed from the repo. Thanks for the notice.
