### ISSUE TITLE
how to unregister the intentreceiver when dfu complete 

### ISSUE THREAD

**Issue by TedWithAHammer** [NordicSemiconductor/Android-nRF-Toolbox#22]
![image](https://cloud.githubusercontent.com/assets/9396361/18827283/9cf2ebc8-8404-11e6-8565-20986b0435fc.png)
what i miss ,i just need access dfu module

**Comment by philips77** [comment]
This has been fixed recently. Please update your DFU library to the newest version, 1.0.4.

**Comment by TedWithAHammer** [comment]
so what is the problem ?which class?

**Comment by philips77** [comment]
Follow those 2 commits
https://github.com/NordicSemiconductor/Android-DFU-Library/commit/0ce71c3f59b8adc2d287a55cca328311fb743328 
https://github.com/NordicSemiconductor/Android-DFU-Library/commit/c1455e2b6fe9debf0eba61dbe18e3d38d83211ac
Which version of nRF Toolbox are you using?

**Comment by TedWithAHammer** [comment]
1.0.0

**Comment by TedWithAHammer** [comment]
thank you ,i've downloaded 1.0.0 ,i'll check the differences
