### ISSUE TITLE
HRM can not find devices

### ISSUE THREAD

**Issue by Kevin-Leung** [NordicSemiconductor/Android-nRF-Toolbox#23]
Hi,I found HRM function module can not search any BLE devices, Did I miss something?

**Comment by philips77** [comment]
Hi, thanks for the report. I'll check it right away and come back to you soon.

**Comment by philips77** [comment]
Are you sure your device advertises with the HRM UUID (0x180D)? The HRM scans with the UUID filter. You may check if your device advertises using either UART profile in nRF Toolbox (there is no filter there), or using nRF Connect application.

**Comment by Kevin-Leung** [comment]
HI, It was the filter problem,I removed the filter and then it works well.thanks for you attention.

**Comment by swapnilghadge2390** [comment]
@Kevin-Leung Can you please guide me which filter you have removed as I am facing the same issue. Thanks in advance
