### ISSUE TITLE
Close the toast 

### ISSUE THREAD

**Issue by duduzai** [NordicSemiconductor/Android-nRF-Toolbox#25]
sometime we get dfu disconnect toast when dfu update sucessful.But i could't find any Toast whole the project.so there are any way to close the toast?forgive me poor english.Thaks any suggests

**Comment by philips77** [comment]
When DFU completes this method is called: https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/master/app/src/main/java/no/nordicsemi/android/nrftoolbox/dfu/DfuActivity.java#L746

**Comment by duduzai** [comment]
thanks i found it.
