### ISSUE TITLE
Gradle sync fails due to wearable for China

### ISSUE THREAD

**Issue by dwyw42** [NordicSemiconductor/Android-nRF-Toolbox#26]
Gradle sync fails with the message: "Failed to resolve: com.google.android.gms:play-services-wearable:7.8.87"

Solution is the top-level build.gradle file is missing the following lines from the allprojects/repositories section (line 17):
```
maven {
   url "${rootProject.projectDir}/google-play-services-7-8-87"
}
```

(Taken from https://developer.android.com/training/wearables/apps/creating-app-china.html#ChinaSDK as referenced in the other gradle.build files)

**Comment by philips77** [comment]
Ups, it must have excluded itself from the commit... Will fix it tomorrow! Thanks!
