### ISSUE TITLE
blt uart received data is discontinuous

### ISSUE THREAD

**Issue by duhongyu** [NordicSemiconductor/Android-nRF-Toolbox#29]
my Bluetooth device send data in 50Hz, but  receive data is not 0.02s at Android6.0 App 
at Android 4.4 is normal

**Comment by philips77** [comment]
The minimum connection interval on Android 5+ is 11.25 ms which should give you 88 Hz. Please check the minimum and maximum connection interval set on your device. A phone is free to choose any value it want from this range.
It's also not an application bug, but a matter of configuration of your device. To debug it you may enable Settings->Developer options->Enable Bluetooth HCI snoop log on your phone, gather data in nRF Toolbox, go back to settings and disable it. Then you'll find a file hci_snoop.log (or something like that) on your phone's main folder sdcard/. You may copy it to your PC and open in Wireshark and check the real packet timestamps. You will also see there the actual connection parameters.
