### ISSUE TITLE
Notifications enabled using Write Command

### ISSUE THREAD

**Issue by philips77** [NordicSemiconductor/Android-nRF-Toolbox#33]
Prior to Android 6 there was a bug on Android. The `gatt.writeDescriptor(descriptor)` method was using parent characteristic's write type, instead of always using WRITE_DEFAULT (Write Request).
nRF Toolbox was ensuring the write type for normal descriptor writes ([see here](https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/fe75efa4cd78162f4a769e2d8076870d81c09041/app/src/main/java/no/nordicsemi/android/nrftoolbox/profile/BleManager.java#L644)), but this workaround wasn't applied during enabling notifications/indications ([here](https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/fe75efa4cd78162f4a769e2d8076870d81c09041/app/src/main/java/no/nordicsemi/android/nrftoolbox/profile/BleManager.java#L729), [here](https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/fe75efa4cd78162f4a769e2d8076870d81c09041/app/src/main/java/no/nordicsemi/android/nrftoolbox/profile/BleManager.java#L519) and [here](https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/fe75efa4cd78162f4a769e2d8076870d81c09041/app/src/main/java/no/nordicsemi/android/nrftoolbox/profile/BleManager.java#L550)).
In all those cases it also should ensure correct write type.

**Comment by samir-eljazovic-sn** [comment]
Hi @philips77 do you know if there is a reference for this issue on Google Issue Tracker?

**Comment by samiraga** [comment]
Hi @philips77 do you know if there is a reference for this issue on Google Issue Tracker?

**Comment by philips77** [comment]
https://issuetracker.google.com/issues/37022798 how about this?

**Comment by samiraga** [comment]
Thanks @philips77
