### ISSUE TITLE
some issue with chip

### ISSUE THREAD

**Issue by myselfgaurav** [NordicSemiconductor/Android-nRF-Toolbox#4]
i am using nordic ble but issue it that it get auto disconnected i want to know is there 

1: some sleep time 
2: how can i debug hardware configuration from chip

**Comment by philips77** [comment]
Hi, you need to provide more details about your issue. 
What phone are you testing on? What device/chip do you connect with?
What is the issue exactly? When the device gets disconnected?
Is you application designed to disconnect after some time of inactivity? 
What do you mean by saying debug hardware configuration?

**Comment by myselfgaurav** [comment]
i am testing it on cyanogenmod 5.0.2 Android. i am using nordic N51822 ble chip.

issue it that it gets disconnected some times say after 1-2 hour automatically.

i have got prebuild chip from some distributer , how can i figure if problem is with android code or chip and also way to debug chip configuration

**Comment by philips77** [comment]
Could you find or post your issue on https://devzone.nordicsemi.com/questions/ portal? I guess it's more related to Android or nRF51 itself than the nRF Toolbox app. As far as I remember the phone I'm working on was several times still connected after a night, but I didn't test it very well. What profile are you testing?
