### ISSUE TITLE
Module Not Defined

### ISSUE THREAD

**Issue by VinayTShetty** [NordicSemiconductor/Android-nRF-Toolbox#41]
After importing the zip file,the android studio is showing. Module not defined.

**Comment by roshanrajaratnam** [comment]
Hi, please clone the [Android-BLE-Library](https://github.com/NordicSemiconductor/Android-BLE-Library) repository within the Android-nRF-Toolbox project. The BLE side of things have been moved in to a separate module to make it easier for maintenance. Let us know how it goes.

**Comment by VinayTShetty** [comment]
![projectextraction_screen_shot](https://user-images.githubusercontent.com/33421892/34479508-5a945b82-efcd-11e7-8058-ebefbcc6e567.PNG)
![screenshot_20171229-173258](https://user-images.githubusercontent.com/33421892/34479509-5ad30256-efcd-11e7-8fe7-6ce478a1fb5e.png)


## Hi roshan i have cloned and compiled the file as below you told but its showing different error now.

**Comment by philips77** [comment]
The Android-BLE-Library project must be cloned into yours DFUupdate folder, and named Android-BLE-Library, without -master.

**Comment by philips77** [comment]
Btw, it's not a good idea to name folders with a name of a branch (master), as you may check you and branch in your local repository.

**Comment by VinayTShetty** [comment]
Can u please send the single  zip file which has completed all the above process.thanks in advance.

**Comment by roshanrajaratnam** [comment]
@VinayTShetty All you have to do is to just move the extracted Android-Ble-Library folder to "Example 1" folder. This Android-Ble-Library module should be located outside our project folder (This case your project folder seems to be Android-nRF-Toolbox-master). Please try this step.

**Comment by VinayTShetty** [comment]
Can u please send the single zip file which has completed all the above process as its again showing the same error .thanks in advance.
@roshanrajaratnam @philips77

**Comment by VinayTShetty** [comment]
@roshanrajaratnam 
I have extracted it outside as u suggested,but its still the same issue.
![screenshot1](https://user-images.githubusercontent.com/33421892/34481298-64f7b39e-efd7-11e7-9077-00bdd3c99767.PNG)
![screenshot2](https://user-images.githubusercontent.com/33421892/34481299-652fd0ee-efd7-11e7-972b-41ec1b0e0865.PNG)
![screenshot3 png](https://user-images.githubusercontent.com/33421892/34481300-65587698-efd7-11e7-8966-1296ae41ec09.jpg)

**Comment by roshanrajaratnam** [comment]
@VinayTShetty check inside the extracted folder to see if its inside another directory of the same name. I think when you extracted, it went in to a sub folder within the folder. Hopefully this should fix your issue and remember to remove "-master". If you look at the settings.gradle file in the project you should see how the folder should look like.

**Comment by VinayTShetty** [comment]
@roshanrajaratnam 
Its seriously not helping its getting more confused.I request you to send a single zip folder which has completed all the above process. so that i can compile and run.

**Comment by roshanrajaratnam** [comment]
Here you go, it's not that hard. Just open the toolbox project from Android studio and you are good to go.
[example.zip](https://github.com/NordicSemiconductor/Android-nRF-Toolbox/files/1600177/example.zip)

**Comment by roshanrajaratnam** [comment]
@VinayTShetty is your issue resolved now?

**Comment by philips77** [comment]
Duplicate of #40

**Comment by VinayTShetty** [comment]
@roshanrajaratnam 
Thank you so much for your effort.
 I got to know how to do it.
Am really thank full to you for Sending that Zip file.
But when i open in android studio application its showing Missing Feature Watch.
How to disable that watch feature.
![screenshot1](https://user-images.githubusercontent.com/33421892/34567129-06389a10-f187-11e7-974d-8e6a4b4c88c6.PNG)
![screenshot2](https://user-images.githubusercontent.com/33421892/34567130-0667f580-f187-11e7-8075-486020b96982.PNG)

**Comment by philips77** [comment]
On the right-top corner of AS, next to the green Play icon, there is a drop-down. Select 'app', not 'wear'.

**Comment by VinayTShetty** [comment]
@roshanrajaratnam 
@philips77 
Thank you Both for Guiding me till here. 
Its Working like a charm,
But i have some question below please answer it..

**Question 1:-**When i click the select Device Button(Screen Shot 2),the scan is not showing my device.

**Question 2:-**I need only DFU firware update to be implemented to my XYZ application,
              i don t require rest of the things which they have implemented like BPM,UART,...etc.
              Can u please guide me on How to get only DFU firmware update code both java and XML and Manifest.

**Question 3:-**My main requirement is devloping an application, that updated DFU through cloud.Not by selecting the Zip files.
           Is that possible..?
           Where i can find any reference for cloud update..?
           Can u both guide me on Update of DFU through Cloud.
![screenshot2](https://user-images.githubusercontent.com/33421892/34596906-6ffa5b8c-f209-11e7-8c4b-2389e511faf8.PNG)

**Comment by roshanrajaratnam** [comment]
@VinayTShetty it would be great if you can post these questions on https://devzone.nordicsemi.com/questions/ as the issues created here are solely for supporting issues related to the app it self. We can take it ahead from there.

**Comment by VinayTShetty** [comment]
@roshanrajaratnam 
@philips77 
Can u help me on this issue please link have posted below
https://github.com/NordicSemiconductor/Android-nRF-Connect/issues/53

**Comment by philips77** [comment]
No. Please don't link to unrelated issues on GitHub just to get out attention.
