### ISSUE TITLE
Different mobile phones sometimes have problems

### ISSUE THREAD

**Issue by Vhaiyue** [NordicSemiconductor/Android-nRF-Toolbox#42]
The use of XIAOMI,SunSang and others handsets can be upgraded every time，but my HuaWei4x can not,  the connection is broken when the Implement progress is almost 15%. I set 55mm delay when send zip,it could success sometimes,but it is slow so much , where  sometime have DeadObjectException. and the oppo R9 can‘t connect device.I am sorry,as a Chinese I am not good at English.can you understant me?

**Comment by philips77** [comment]
Try enabling PRNs, try value 12, if doesn't work some lower until 1. Your find required methods in the DfuServiceInitiator.
