### ISSUE TITLE
Android-nRF-Toolbox  in Android Studio . get Error:Failed to find Build Tools revision 27.0.1

### ISSUE THREAD

**Issue by jiaxunye** [NordicSemiconductor/Android-nRF-Toolbox#46]
I downloaded Source Code on: https://github.com/NordicSemiconductor/Android-nRF-Toolbox/releases

I unzipped this volume in My Workspace, I run Android Studio 1.0.1 and I opened the project.

At the moment the code is displayed in the IDE, Messages window shows the following:

Error:Failed to find Build Tools revision 27.0.1

In the picture below, you can see the problem:

**Comment by philips77** [comment]
It requires Android Studio 3.0.1 and other tools that come with it, including Build Tools 27.0.1. You may download them from AS if the build fails with a single click (there'll be a button on the build console). But I recommend downloading the newest AS, it'll tell you to automatically update the project.
Also, remember about the BLE library as stated in the Readme.
