### ISSUE TITLE
Renaming mBinded to mBound in BleProfileService?

### ISSUE THREAD

**Issue by tamberg** [NordicSemiconductor/Android-nRF-Toolbox#47]
Consider renaming mBinded to mBound in https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/master/app/src/main/java/no/nordicsemi/android/nrftoolbox/profile/BleProfileService.java#L82

**Comment by philips77** [comment]
I've just fixed this and https://github.com/NordicSemiconductor/Android-BLE-Library/issues/8 on develop branch. As the new version will require some changes to be migrated from 1.0 I also decided to fix those old spelling errors.
