### ISSUE TITLE
cannot Run after downloading the source folder in android studio.

### ISSUE THREAD

**Issue by VinayTShetty** [NordicSemiconductor/Android-nRF-Toolbox#48]
I have downloaded the zip folder from the [link](https://github.com/NordicSemiconductor/Android-nRF-Toolbox) after opening in android android studio its not showing the option s for Run.
I have attached the screen Shot.
![capture](https://user-images.githubusercontent.com/33421892/39918581-901280c4-552e-11e8-9b23-4684b98cb109.PNG)

**Comment by philips77** [comment]
You have to resolve the issues first. I guess the :ble module could not be found. Make sure you also have the Android-BLE-Library project, and the path to ble module on nRF Toolbox's settings.gradle file points to ble folder in BLE Library.

**Comment by philips77** [comment]
Same that you had to do with nRF Blinky. Then i think sync may work and app and wear options should be shown.

**Comment by philips77** [comment]
The nRF Toolbox now imports BLE Lib from jcenter. This should now work out-of-the box after cloning the project without the need to set up the library.
