### ISSUE TITLE
Unable to find a matching configuration of project :wear:

### ISSUE THREAD

**Issue by lirunqiuqiu** [NordicSemiconductor/Android-nRF-Toolbox#49]
Android version is 3.12,  gradle version is 4.1

Unable to find a matching configuration of project :wear:
  - Configuration 'debugApiElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
      - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
  - Configuration 'debugMetadataElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Metadata'.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
      - Required org.gradle.api.attributes.Usage 'java-api' but no value provided.
  - Configuration 'debugRuntimeElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
      - Required org.gradle.api.attributes.Usage 'java-api' and found incompatible value 'java-runtime'.
  - Configuration 'releaseApiElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
      - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
  - Configuration 'releaseMetadataElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Metadata'.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
      - Required org.gradle.api.attributes.Usage 'java-api' but no value provided.
  - Configuration 'releaseRuntimeElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
      - Required org.gradle.api.attributes.Usage 'java-api' and found incompatible value 'java-runtime'.

**Comment by philips77** [comment]
Switch from wear to app in the drop down menu next to the Run button in Android Studio.

**Comment by philips77** [comment]
It's that you don't have a wear device to run on. Just change to app and it will run on the phone.

**Comment by lirunqiuqiu** [comment]
Thanks for your suggestion. Didn't the app should depend on wear ? I can't run the app. Request class is in wear.
![image](https://user-images.githubusercontent.com/38482233/40916414-37f97138-6832-11e8-8764-6b100438b1c6.png)

**Comment by philips77** [comment]
This should be fixed now.
