### ISSUE TITLE
Unable to find a matching configuration of project :ble: None of the consumable configurations have attributes.

### ISSUE THREAD

**Issue by msrajanadar** [NordicSemiconductor/Android-nRF-Toolbox#50]
https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/02a7659451f64e7db823477678b67d4d5951e505/app/build.gradle#L58

i got below solution for the issue 
    // BLE library
implementation 'no.nordicsemi.android:ble:1.1.0'

**Comment by philips77** [comment]
Hi,
I've updated the project, now it depends on the BLE Lib from jcenter. And, actually, imports version 1.2.0 of the ble library.
Also, I'll move the current master branch to some other branch, and merge develop into master. Develop branch is using BLE Library v2.0-alpha1.
