### ISSUE TITLE
error: cannot find symbol variable Request

### ISSUE THREAD

**Issue by Roarin** [NordicSemiconductor/Android-nRF-Toolbox#53]
I am tryonnng to build the library in android studio. However I keep getting this error.I have tried disabling minify, setting sdkversion . Could someone please help me out?

I have the same folder structure as suggested.

**Comment by philips77** [comment]
Hi, there's a missing import. I moved the Request class from an inner class, to a standalone class in the BLE Library, but didn't update the app. I'll fix it today.
I'm about to release version 2 of the BLE Library, which is available now on `develop` branch. You may try it:
Checkout `develop` branches on BLE Library, nRF Toolbox and another project called BLE Common Library, also available on our GitHub.
