### ISSUE TITLE
Rewrite the app in Kotlin

### ISSUE THREAD

**Issue by devabacus** [NordicSemiconductor/Android-nRF-Toolbox#60]
Do you have any plan to transfer your code into very popular kotlin language?

**Comment by philips77** [comment]
Yes, eventually. But right now we are busy with other tasks :(

**Comment by devabacus** [comment]
Can I meet some problems if I'm gonna write app on kotlin using your libs written on java (ble,scanner,dfu,log)?

**Comment by philips77** [comment]
Everything should work with kotlin. If you find any problems (like a null in non-null method, etc) please tell us.
