### ISSUE TITLE
Android-nRF-Toolbox-2.6.0 and Android-BLE-Library-1.2.0

### ISSUE THREAD

**Issue by lzxsmile** [NordicSemiconductor/Android-nRF-Toolbox#61]
I use Android-BLE-Library-1.2.0 and Android-nRF-Toolbox-2.6.0,
EER: class Request not to find,why?
![_20181201005517](https://user-images.githubusercontent.com/36809169/49303118-e2962d80-f503-11e8-9a70-da4cc60bc3f6.png)
![_20181201005552](https://user-images.githubusercontent.com/36809169/49303124-e9bd3b80-f503-11e8-8f61-fdc68793fef7.png)

**Comment by philips77** [comment]
Request was moved out of BleManager to a standalone class. Just add import as it will suggest.

**Comment by lzxsmile** [comment]
i import the class,that method writeCharacteristic(mAlertLevelCharacteristic) 
![_20181201085556](https://user-images.githubusercontent.com/36809169/49322115-4e4dba00-f547-11e8-854c-4d3a479387d1.png)
will err.

**Comment by lzxsmile** [comment]
![_20181201085135](https://user-images.githubusercontent.com/36809169/49322124-645b7a80-f547-11e8-8453-92b109eff574.png)

**Comment by lzxsmile** [comment]
import the first one
![_20181201090837](https://user-images.githubusercontent.com/36809169/49322252-ed26e600-f548-11e8-95b1-8640fe5e8897.png)
?

**Comment by philips77** [comment]
Yes, the first one, as it suggests. Also, the data parameter has to be given as a parameter, not "inside" the `BluetoothGattCharacteristic` object.
That means, you should do:

```java
writeCharacteristic(mAlertLevelChar, someData);
```
instead of:
```java
mAlertLevelChar.setValue(someData);
writeCharacteristic(mAlertLevelChar);
```
This is to make sure the data you write will not override any data received in a notification, which may happen at the same time.
