### ISSUE TITLE
Proguard error Android Studio 3.3

### ISSUE THREAD

**Issue by bluefirepatrick** [NordicSemiconductor/Android-nRF-Toolbox#63]
I have found that the proguard-rules.pro file throws an error in Android Studio 3.3  It seems to be because the proguard file references a directory instead of a jar -which may be a requirement that changed somewhere along the way.

It's the first line of the file:
-libraryjars ../app/libs

I was able to fix it by adding the jar file to the line:
-libraryjars ../app/libs/achartengine-1.2.0.jar

which is the only jar in there.  I would he happy to submit a pull request if you would like me to.  I just thought I would mention it in case it helps.

Thanks for all the great Android code by the way.  I have been enjoying it.

**Comment by philips77** [comment]
Hello! Please submit the PR. Thanks!

**Comment by ananthrajsingh** [comment]
I also had the same issue.

**Comment by philips77** [comment]
Fixed by #68
