### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by kanubhav** [NordicSemiconductor/Android-nRF-Toolbox#65]
I downloaded the zip file and extracted in my desktop. I opened the file in AS and build it. When pressed the run button after some time it flashed me an error.
Error: C:\Users\H341261\Downloads\example\Android-nRF-Toolbox\app\..\app\libs, File not found: C:\Users\H341261\Downloads\example\Android-nRF-Toolbox\app\..\app\libs (Access is denied).
Can you tell me how to resolve this error?

**Comment by philips77** [comment]
You should see this file in *libs* folder:
https://github.com/NordicSemiconductor/Android-nRF-Toolbox/tree/master/app/libs
Check Windows permissions for those folders. Perhaps it prevents from opening a jar file?
You may also clone the repo using git, not by downloading it in ZIP and try that way.
Sorry, but I can't help you more. It's related to your local setup on your computer.

**Comment by kanubhav** [comment]
I tried to clone the repo using git but I am getting the same error.
In the folder: 
https://github.com/NordicSemiconductor/Android-nRF-Toolbox/tree/master/app/libs
the .jar file is not opening for me.
I checked the windows permission also for that folder but still, I am not able to resolve the error.

**Comment by wolfgang-elsner** [comment]
I have tried the same and have also the same error.

**Comment by kanubhav** [comment]
Can you please provide a solution for the above issue!

**Comment by thinkfeed** [comment]
maybe you shouldn't upgrade your com.android.tools.build:gradle version to latest

**Comment by kanubhav** [comment]
Thanks @thinkfeed it worked.

**Comment by philips77** [comment]
Fixed by #68.
