### ISSUE TITLE
DFU Services discovered error 129 (0x81)

### ISSUE THREAD

**Issue by IkeLiang** [NordicSemiconductor/Android-nRF-Toolbox#66]
I use the Phone(HUAWEI P9 Lite) and Android-nRF-Toolbox app to do Device Firmware Update.
But it always error when the phone connecting devices that are in DFU mode.

nRF connect app log show:
[Log 2019-02-27 094419.txt](https://github.com/NordicSemiconductor/Android-nRF-Toolbox/files/2924424/Log.2019-02-27.094419.txt)
[Log 2019-02-27 095006.txt](https://github.com/NordicSemiconductor/Android-nRF-Toolbox/files/2924425/Log.2019-02-27.095006.txt)

```
nRF Connect, 2019-02-27
DfuTarg (ED:AE:B6:19:2E:36)
V	09:32:46.932	Connecting to ED:AE:B6:19:2E:36...
D	09:32:46.933	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE)
D	09:32:47.119	[Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	09:32:47.119	Connected to ED:AE:B6:19:2E:36
D	09:32:47.140	[Broadcast] Action received: android.bluetooth.device.action.ACL_CONNECTED
V	09:32:47.147	Discovering services...
D	09:32:47.147	gatt.discoverServices()
D	09:33:17.630	[Callback] Services discovered with status: 129
E	09:33:17.639	Error 129 (0x81): GATT INTERNAL ERROR
D	09:33:17.645	[Callback] Connection state changed with status: 133 and new state: DISCONNECTED (0)
E	09:33:17.645	Error 133 (0x85): GATT ERROR
I	09:33:17.645	Disconnected
D	09:33:19.648	[Broadcast] Action received: android.bluetooth.device.action.ACL_DISCONNECTED
```
How can't I fix the issues?

**Comment by philips77** [comment]
There is something wrong with your device. Did you try with the SDK examples? The service discovery terminates on a timeout 30 sec after it started. The device seems not to respond.
Please, ask your question on [DevZone](http://devzone.nordicsemi.com/) as it's related more to the fw side, not the DFU library or nRF Toolbox app.
