### ISSUE TITLE
DFU crash after 2.7.0 update

### ISSUE THREAD

**Issue by StephaneJuban** [NordicSemiconductor/Android-nRF-Toolbox#69]
Since the new version (2.7.0) when I want to upload a new firmware update the app goes back to home page.

Everything was working great before.

I'm using a Google Pixel 2.

**Comment by philips77** [comment]
Thanks for the feedback. I'll fix it asap. It's a proguard issue in the project, it was working in debug.

**Comment by StephaneJuban** [comment]
Ok no problem thanks for the quick answer.
I use nRF Connect as a backup solution in the meantime :)
