### ISSUE TITLE
How to add the Manufacturer Logo like in NRF Connect Alp

### ISSUE THREAD

**Issue by ethanHuntoo7** [NordicSemiconductor/Android-nRF-Toolbox#80]
I checked the NRF Connect App. it is showing the Logos like Mac, Windows and Uart icons at left for every device in Scanning list.
I want to know how to find that Device Type or Manufacturers Info to filter it.

**Comment by philips77** [comment]
nRF Connect displays icons based on the content of the advertising data. Different known devices advertise with different services, have unique syntax in service data or manufacturer data, or have some known pattern in the name. Check the data advertised by your device to find the best pattern.
