### ISSUE TITLE
nRF Toolbox(Ver 2.8.0) fail DFU on running Android 9

### ISSUE THREAD

**Issue by faithmaker** [NordicSemiconductor/Android-nRF-Toolbox#86]
nRF Toolbox(Ver 2.7.3) is OK.
i use bootloader in SDK(nrf5_SDK_15.2.0_9412b96)

**Comment by philips77** [comment]
Oh, that's bad. What error do you get?

**Comment by philips77** [comment]
Ok, I have it. It's R8 configuration related to Gson. I'll fix it asap. Thank you for creating the issue!

**Comment by philips77** [comment]
Fix released in 2.8.1.
