### ISSUE TITLE
Gatt Write Not Permit

### ISSUE THREAD

**Issue by jimakos96** [NordicSemiconductor/Android-nRF-Toolbox#98]
Hi 
I am trying to use ble to communicate via UART on the adafruit feather sense board and i am getting the following message .
Does anybody know what is causing it ?

![image](https://user-images.githubusercontent.com/24825355/110338314-86e67300-802f-11eb-836d-77fa4fecd1c9.png)

**Comment by philips77** [comment]
Old handles of the device has been caches on Android phone. To invalidate caches restart Bluetooth, or use nRF Connect app: connect to the device, select top-right menu and tap *Refresh services*.
